class AddSpreeEsewaPaymentSource < ActiveRecord::Migration[6.0]
  def change
    create_table :spree_esewa_payment_sources do |t|
      t.float :amount # Total payment amount of product or service
      t.string :scd # Merchant code provided by esewa
      t.string :pid # A unique ID of product or item or ticket generated by merchant for payment
      t.string :rid # A unique payment reference code from eSewa generated on successful transaction
                    # Necessary for the payment verification
      t.integer :payment_method_id
      t.integer :user_id
      t.timestamps
    end
  end
end
